// Translation texts for each language
const translations = {
    en: {
        tableHeader1: "Date",
        tableHeader2: "Kilometers",
        tableHeader3: "Liters",
        tableHeader4: "Fuel Type",
        tableHeader5: "Petrol Station",
        tableHeader6: "Price per Liter (€)",
        tableHeader7: "Total Cost (€)",
        tableHeader8: "Average Consumption (L/100km)",
        addRefuel: "Add Refuel",
        noEntries: "No refuel log entries yet.",
    },
    fi: {
        tableHeader1: "Päivämäärä",
        tableHeader2: "Kilometrit",
        tableHeader3: "Litrat",
        tableHeader4: "Polttoainetyyppi",
        tableHeader5: "Bensa-asema",
        tableHeader6: "Hinta per litra (€)",
        tableHeader7: "Kokonaiskustannus (€)",
        tableHeader8: "Kulutus (L/100km)",
        addRefuel: "Lisää tankkaus",
        noEntries: "Ei vielä tankkausmerkintöjä.",
    },
    sv: {
        tableHeader1: "Datum",
        tableHeader2: "Kilometer",
        tableHeader3: "Liter",
        tableHeader4: "Bränsletyp",
        tableHeader5: "Bensinstation",
        tableHeader6: "Pris per liter (€)",
        tableHeader7: "Total kostnad (€)",
        tableHeader8: "Genomsnittlig förbrukning (L/100km)",
        addRefuel: "Lägg till tankning",
        noEntries: "Inga tankningsanteckningar ännu.",
    },
    ru: {
        tableHeader1: "Дата",
        tableHeader2: "Километры",
        tableHeader3: "Литры",
        tableHeader4: "Тип топлива",
        tableHeader5: "АЗС",
        tableHeader6: "Цена за литр (€)",
        tableHeader7: "Общая стоимость (€)",
        tableHeader8: "Средний расход (л/100км)",
        addRefuel: "Добавить заправку",
        noEntries: "Пока нет записей о заправках.",
    },
    fr: {
        tableHeader1: "Date",
        tableHeader2: "Kilomètres",
        tableHeader3: "Litres",
        tableHeader4: "Type de carburant",
        tableHeader5: "Station-service",
        tableHeader6: "Prix par litre (€)",
        tableHeader7: "Coût total (€)",
        tableHeader8: "Consommation moyenne (L/100km)",
        addRefuel: "Ajouter un ravitaillement",
        noEntries: "Aucune entrée pour le moment.",
    },
    et: {
        tableHeader1: "Kuupäev",
        tableHeader2: "Kilomeetrid",
        tableHeader3: "Liitrid",
        tableHeader4: "Kütuse tüüp",
        tableHeader5: "Bensiinijaam",
        tableHeader6: "Hind liitri kohta (€)",
        tableHeader7: "Kogumaksumus (€)",
        tableHeader8: "Keskmine kulu (L/100km)",
        addRefuel: "Lisa tankimine",
        noEntries: "Seni pole tankimismärkmeid.",
    },
};
